### ISSUE TITLE
Add p:compress/p:uncompress steps

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#114]
Compress takes serialization parameters and compresses the serialized representation using [insert favorite compression flavor here]. Uncompress reverses the process. Each takes exactly one document.

**Comment by eriksiegel** [comment]
Is there any compression format that we define as mandatory here?
Or are all the supported compression formats completely implementation defined?

**Comment by gimsieke** [comment]
I’d support making zip (we already have it for archives, we can also use it on single files) and gzip mandatory.

**Comment by eriksiegel** [comment]
Then I suggest to _only_ prescribe supporting `zip ` because we do this in p:archive etc. also.

**Comment by eriksiegel** [comment]
But zip is an archive format (compressing *and* container format for multiple files). Excuses for my ignorance,but is there also something like a zip *compression* format and if we state compression format zip is that clear enough for implementors?

**Comment by gimsieke** [comment]
I don’t think there is an independent zip compression format. It can use a variety of compression methods but I think it always creates an archive (that may contain a single file).

We can explain that using `zip` as a compression method is equivalent to creating a zip archive with a single entry.

Because of its widespread use, I’d still support also stipulating that an implementation provide the `gzip` format.

**Comment by eriksiegel** [comment]
> Because of its widespread use, I’d still stipulate that an implementation support the gzip format.

Would you like to add this to the mandatory formats for `p:archive` and `p:unarchive` also? 

I would like to hear the opnion of our implementors @ndw  and @xml-project also about this.

**Comment by gimsieke** [comment]
No, `gzip` doesn’t do archiving. If we wanted to cover the archive format that often comes gzipped, we’d need to require `tar` support in the archive steps. I’m not against requiring tar over there.

**Comment by eriksiegel** [comment]
Let's leave the `p:(un)archive` steps as they ar now for the moment.

Then I suggest specifying two mandatory formats (beside any implementation defined ones) for `p:(un)compress`:
* `zip` which results in a zip file with a single entry. `p:uncompress` expects a zip file with a single entry, multiple entries result in an error.
* `gzip` that compresses usign the gzip format

@ndw, @xml-project ?

**Comment by gimsieke** [comment]
Let’s discuss whether `p:uncompress` should behave as `p:unarchive` when the compression method is `zip`. 

I think this satisfies user expectations. 

If we think this is weird then we should reconsider requiring `zip` as a `p:compress` method.

**Comment by eriksiegel** [comment]
Fine with me, no preferences, I concur. Maybe you or somebody else can put this on the agenda for the call tomorrow (which I unfortunately cannot attend) and let me know the results?

I already have a skeleton text for `p:compress` ready, just need to know about the supported formats.

**Comment by gimsieke** [comment]
Will do

**Comment by xml-project** [comment]
@eriksiegel Sorry, I am currently on the road, so it‘s difficult to look at an issue. Will look at it tomorrow when I am on train back home.
Two remarks:

1. If you and/or @gimsieke wants to add new features, please remove the „Consensus reached“ tag because it is confusing.
2. I have used gzip to compress a file and send it, but I have newer done this for a single file with zip because of creating a manifest... Is there really a use case for this?

**Comment by eriksiegel** [comment]
@xml-project I don't think we're adding new features, just fleshing out some details. The consensus was that we wanted a p:(un)compress. As soon as you then start to write the spec, you find out that some details (like compression formats) are still unspecified. That does not changes the consensus IMHO....

I think you're right about the zip format here: It's re-doing something you can just as easily accomplish with a p:archive step. Probably falling into the over-engineering trap.

**Comment by gimsieke** [comment]
An argument in favor of `p:compress` also doing zip archives for single files would be if you needed to create a manifest first. But you don’t need to supply a manifest, you can simply pipe a single file into `p:archive` and it will be zipped. 

Let’s discuss ist tomorrow nevertheless.

**Comment by eriksiegel** [comment]
I'm writing the spec for `p:uncompress` and there is something I would like to discuss beforehand:

The `p:uncompress` actually does two things:

1. It uncompresses the document appearing on its `source` port. This produces a binary/text something.
1. It *then* tries to interpret this into an internal XProc document, right? So if you compressed an XML document and uncompress it, what you get is an XML document on the `result` port.

This means the step's options need to cater for both stages. This in  turn means we have two parameter maps to pass as an option. One for the uncompress parameters and one for the interpretation parameters (which can be defined as behaving like in `p:load`). For the second stage there's also an (optional) `content-type` parameter (behaves roughly like in `p:load`).

This reasoning leads to the following questions:
1. Is this reasoning correct?
1. I don't think we have any other step that has two parameter options. How to call them? I tentatively decided on  `uncompress-parameters` and `parameters` but it feels ugly. Any other preferences?
1. This two stage processing also happens on the `p:unarchive` step and we don't say anything about it. Any need to amend `p:unarchive`? Any more steps with the same problem?

**Comment by xml-project** [comment]
Good catch. Some random remarks:

1. EXProc's uncompress step assumed that the result would be an XML document. Since we now have different document types, I think a required option `content-type` is necessary.
2. IMHO for p:unarchive the situation is different because a processor can guess required content-type based on the entry name. Just like we do with p:document.
3. Im am not sure we really need the second parameter (like on p:load):
 - For XML document the only defined key is DTD-validation. Do we need this with uncompress?
 - For HTML, text, and binary `parameters` is completely implementation-defined.
- Brings us to JSON documents where we follow XPath with some parameters. But these parameters basically control how strict the JSON parser behaves to invalid JSON. Not sure it is worth to cover this case here.

If I have a compressed document I know to be a JSON, but an incorrect JSON, I could always choose `p:uncompress/@content-type='text/plain'` followed by a cast-content-type.

But as I said: Just some random thoughts. The only thing I am pretty sure about is that we need an option `content-type`.

**Comment by eriksiegel** [comment]
@xml-project Sounds very reasonable. What I suggest then is:

- A `parameters` option to control the uncompress (implementation defined)
- A `content-type` option.

Question: Should the `content-type` option be mandatory or optional? Is it reasonable to have `p:uncompress` try to guess the content-type of the uncompressed document (implementation defined)?

It could for instance first try to interpret it as XML, if not successful as JSON, if not successful see if it looks like text, if not it is a binary.

**Comment by xml-project** [comment]
👍 
Auto-guessing is an interesting idea. Guess 1 and guess 2 works, but how to guess if something is a text or a binary?
If there is a way to do this, I think an optional option is reasonable.

**Comment by eriksiegel** [comment]
Almost done (?). There is an error condition missing. See comments on #221
