### ISSUE TITLE
Incorrect definition for archive manifest c:entry

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-steps#118]
The definition for a `c:entry` element in an archive's manifest now reads `anyElement*`. This should be `anyNode*` (does something like that exists? Maybe just mixed contents with any elements?).

If we keep it `anyElement*` you will never be able to specify text contents in a manifest, which is rather handy!

**Comment by gimsieke** [comment]
You can, if you wrap it in an element (that in turn may have any child nodes I guess, at least this was the premise on which I allowed almost any child element)

**Comment by eriksiegel** [comment]
How do we then make the distinction between an entry with just text and an entry with a single root element? There is no content-type attribute...

**Comment by gimsieke** [comment]
I think I see what you mean here. Your assumption probably is that `c:entry` can hold the actual contents of an archive member. This is not the case. 
Please correct me if my interpretation of your question is wrong.

When you create a manifest, any `c:entry` child nodes will be ignored (as will be specified once we fix “When the c:entry elements has any child nodes, it is ignored.” → “When the c:entry elements has any child nodes, they are ignored.”). The archive contents will be pulled from the `source` port or, if there’s no document with a matching base URI, from the location given by `c:entry/@href`.

In the manifest that comes out on the `report` port of `p:archive`, `c:entry` wasn’t meant to hold the actual content of an archive entry, either. We allowed children in `c:entry` in order to allow archiving tools to enrich entries with additional metadata or error reporting that isn’t covered by the existing attributes such as `@level`, `@comment`, `@method`, and implementation-defined attributes.

**Comment by eriksiegel** [comment]
There seems to be a difference of opinion here. What I meant is (and probably said wrong in London):
When the c:entry elements has any child nodes, it is ignored. ==> When the c:entry elements has any child nodes, the **href attribute** is ignored

So what I would like is that the `p:archive` steps looks for the contents of the archive entries in three ways (in this order!):

1. If `c:entry` has any contents, this will become the contents of the entry. `c:entry/@href` is ignored.
1. If the `href` attribute has the same value as the base URI of one of the document appearing on the `source` port, this is used
1. The `href` attribute is interpreted as a URI and the document is loaded from disk or whatever.

We can change the mechanism, but for some of my use-cases it is rather important that you can specify archive entry contents in the manifest. I do would like to have something that enables that.

**Comment by eriksiegel** [comment]
Closed because of decision on #116
