### ISSUE TITLE
Clarify specification of p:validate-with-schematron

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#17]
The current version of the specs says:

> The parameters option provides name/value pairs which correspond to Schematron external variables.

Does this mean, they are also passed to the final stage of processing, when the generated XSLT is applied to the document?

This issue was raised for XProc (1.0) [before](https://github.com/ndw/xmlcalabash1/pull/146) by @gimsieke, but the problem is not solved with the current version of the specs.

I propose to use the solution of XMLCalabash as standard, viz. pass the parameters also to stage 4 to make it accessible with <xsl:param />.

**Comment by AndrewSales** [comment]
Some time later...

I just noticed this: can the signature [here](https://github.com/xproc/3.0-steps/blob/master/step-validation/src/main/xml/specification.xml#L139) use `#DEFAULT` instead of `#ALL`?
If no default phase is given in the schema (configured externally using `#DEFAULT`), then all patterns (`#ALL`) are active.
If the default value of this option is `#ALL` and their schema specifies a `defaultPhase` then the user has to set the desired default **twice**, once in the schema and again in the pipeline processor, in order to override the, err, default.

**Comment by ndw** [comment]
Overetaken by events; this is now in the validation spec.
