### ISSUE TITLE
p:xquery and "application/xquery"

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#184]
Related to #183 : [XQuery](https://www.w3.org/TR/2017/REC-xquery-31-20170321/#id-mime-type) defines media type "application/xquery", but this is not accepted by p:xquery which only takes "application/xml */*+xml text/*" for port `query`.
I think we should fix this by making documents with "application/xquery" text documents.

**Comment by gimsieke** [comment]
Yes, I think we should

In the same vein, shouldn’t we then also consider `application/javascript` as `text`, too? There might be Javascript-executing steps in the future. 

The following should go into an issue of its own: Shouldn’t we include `application/json` in `text`, too? So that every text-processing step like `p:string-replace` (which doesn’t accept `text` or `json` yet but really should at least accept `text`) or `p:text-join` may be used to process JSON documents as text documents? 

If a step accepts both `json` and `text`, there need to be precedence rules, such as: If a step treats JSON input differently than text input and if the input arrives as `application/json`, treat it as JSON and not as text.

**Comment by ndw** [comment]
I'm fine with making "application/xquery" documents into text. And "application/javascript" (I already have a cx:javascript step :-) )

However, "application/json" documents aren't text. They're maps or arrays or simple atomic types.

**Comment by gimsieke** [comment]
Right. If I want to apply raw text manipulation to a JSON file/document, I can override the content type to `text/plain` when loading the file, or serialize the structure using the JSON method.

**Comment by xml-project** [comment]
Addressed with [specification pr](https://github.com/xproc/3.0-specification/pull/858) 858

**Comment by xml-project** [comment]
Fixed with specification pr 858
