### ISSUE TITLE
We need to say more about the processing of entry names in p:unarchive

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#245]
In p:unarchive we use the entry name in the ZIP to filter the entry and to create the base URI of the extracted document.

But: An entry name (according to ZIP) allows any UTF-8 character. So we have to
(1) That the entry name is CONVERTED to a valid instance of xs:anyURI
(2) We have to say whether this happens before or after the filtering (because users will have to write different regex expressions).

**Comment by xml-project** [comment]
After thinking about it, I think the most reasonable way to handle this problem is to raise a dynamic error if the entry name of an entry passing the filting cannot be made into a valid XS_AnyURI.
Thought?

**Comment by xml-project** [comment]
The current specs does not anything about this, so I try to find a solution for the problem. If we say, that the entry name needs to be url-escaped, then we need to detemine:
1. Is is done before or after the filtering?
2. Which algorithm is used? 

For p:load, p:document etc. we require the resources to have valid xs:anyURI by nature, so there is no convertion done. If we use any of XPath's standard function, we loose IRIs and have URIs (but only in the special case of documents extracted from an archive).
Since it is an edge case which only applies, if the entry name has a "%" not followed by hex, if it starts with a ":" or contains more than one "#" I thought, raising an error would be fine.

**Comment by gimsieke** [comment]
Just saying that Zip entries can be (and sometimes are actually) encoded as [CP437](https://de.wikipedia.org/wiki/Codepage_437) (see, for ex., https://stackoverflow.com/questions/13261347/correctly-decoding-zip-entry-file-names-cp437-utf-8-or), and sometimes it is not properly flagged which encoding is used.

I’d say that an implementation needs to be able to convert both CP437 and UTF-8 to URIs. In the case of CP437, first create an UTF-8 representation, and then use `p:urify()`. 

Currently it is specified that implementations are free to leave multibyte UTF-8 chars unescaped, but we should maybe stipiulate that they need to be strictly escaped in order to support predictable matching.

**Comment by xml-project** [comment]
So gentleman, I was on the wrong track: As Michael Kay pointed out in an answer on [stackoverflow](https://stackoverflow.com/questions/33826104/can-xsd-type-of-anyuri-contain-spaces) that lexical space for xs:anyURI is not restricted any more.
So no error can occur here.
