### ISSUE TITLE
Error XD0064 is void

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#248]
This error reads:

> It is a dynamic error if the `c:entry/@href` attribute in a p:archive step manifest is present and its value is not a valid xs:anyURI.

or

> It is a dynamic error (err:XD0064) if the href URI is not a valid xs:anyURI.

The specs on [xs:anyURI](https://www.w3.org/TR/xmlschema11-2/#anyURI) define it as matching the XML char production. This means (to my reading) that this error could never to raised, once on XProc document is parsed. Right?

I propose therefor to say, that @href must by a valid URI par rfc3986. Does this make sense to anyone?

**Comment by ndw** [comment]
Are we really going to insist that implementations test the value?

**Comment by gimsieke** [comment]
Stipulating strict RFC 3986 compliance might force you to reject manifest entries with unescaped UTF-8 octets or with `file:/home` instead of `file:///home` although they might just resolve fine on most users’ machines. Postel’s law suggests that we accept these unorthodox yet widespread shortcuts. If they don’t resolve to resources, you are free to give users a hint that non-conformance with RFC 3986 might cause the issue.

You need to apply some URI normalization to `c:entry/@href` before comparing it to the `base-uri` document property of the incoming documents. Things like `FILE:/c:/` → `file:///C:/`, `file:///home//dave/foo/../bar` → `file:///home/dave/bar`, etc.

Only certain things that are known as problematic may be flagged as an error, like `file://foo/bar` on Unix-like systems (on Windows it’s ok; `foo` is then interpreted the host name component in a UNC path).

We can think about keeping the error code for situations when an implementation deems a purported URI as “too far off”, but the criteria it applies may be implementation-dependent.

**Comment by xml-project** [comment]
I think we should follow the [XPath and XQuery](https://www.w3.org/TR/xpath-functions-3/#func-doc) function definition and define href on p:load, p:document, p:with-input, p:input and p:output (hope I did not miss one) as an instance of xs:string and raise a dynamic error, if this string is not a valid URI reference. (@gimsieke XPath is strict here, so I think we could dare to be strict to.)

I am not sure how to deal with the href in the manifest document of p:archive because it serves a double of either identifing a document contained on port `source`. If no such document is provided, the specs say, 

> the value of the href attribute is interpreted as a URI and the document is loaded from this location

So here it is clear to me, that it has to be a valid URI reference and that it would be user friendly to raise an error stating, that the load failed _because the uri is defective_.

Does this make sense?

**Comment by xml-project** [comment]
I think @ndw is right. Lets just remove this error. It is up to the pipeline author to provide a URI that is valid from the used file system.

**Comment by xml-project** [comment]
But see @gimsieke's [comment](https://github.com/xproc/3.0-steps/pull/255#issuecomment-550904741) arguing for the opposite. (If I understood it right). If not, I am pretty sure however that this comment is related to this issue.

**Comment by gimsieke** [comment]
IIRC we decided at our last call that we want to have a check (and an autocorrection), potentially deferred to when the processor is actually reading or writing from/to a URI.

**Comment by ndw** [comment]
Per discussion at the f2f, we will change the message to say that it has to be valid by the RFC rather than by xs:anyURI.
