### ISSUE TITLE
Not sure whether p:unarchive is right

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#268]
If I understand our consensus in Cologne regarding base URIs right, then a document flowing out of a step either has NO base URI (like c:result in p:count) or has a valid absolute URI according to the RFC specification. Right?

If so, we need to fix p:unarchive, because it is not certain, that every document coming out this step has an RFC valid URI. The base against which relative URI of the archives entry are resolved is valid (or an error is raised), but the entries name itself may raise the problem. Just think of an entry named "%gg ##". The resulting base URI of the document is not valid. Right?

As a solution I propose, that p:urify is implicitly called with the entrie's name as first param and either "relative-to" or the archive's URI as second param. It is an error, if the resulting string is not a valid URI.

We voted against implicit use of p:urify in Cologne but I think we need it in this case because the pipeline author has no way to make sure, the entries in the archive result in valid URIs.

Did I missunderstand or miss something?

**Comment by xatapult** [comment]
Can't we use percent encoding for these kinds of entries? Isn't that what you're supposed to do then?

**Comment by xml-project** [comment]
Yes, but how would you do this? Suppose you get a zip from a customer. If she did not encode the names of the entries right, you would have to change them by hand before you can open the archive in a pipeline. At least I think so, this is why I proposed an implicit call of "p:urify()" to do the %encoding.
What did I miss?

**Comment by gimsieke** [comment]
Yes, `p:urify()` should be implicitly called on the entries’ names, resolving them against the archive URI or to the URI given in `relative-to`. 

Speaking of `p:urify()`: I admit it is a bit complicated, exacerbated by Windows drive letters, Windows UNC paths, and my relative incompetence wrt Git, but could someone have a look at PR #896?

Rendered: https://gimsieke.github.io/3.0-specification/issue889/head/xproc/#f.urify

Diff: https://github.com/xproc/3.0-specification/pull/896/files 

The three normalization procedures applied to paths are percent encoding/decoding according to Sect. 2.4 of RFC 3986 and path contractions (`..` eating its parent path, `.` segments eliminated) according to Sect. 3.3., and slash normalizations like `file:/tmp` to `file:///tmp`.

Another issue with Zip archives (not with `p:unarchive` in general) is that a step should be prepared to see entry names encoded in CP 437 instead of UTF-8. I think we can say if `p:urify()` fails for an entry, `p.unarchive` may try to read a Zip’s entry name as if it were encoded as CP 437, transform the octets into an UTF-8 string and then apply `p:urify()`.

**Comment by xatapult** [comment]
I have no problem at all with his if this does the trick:

> Yes, p:urify() should be implicitly called on the entries’ names, resolving them against the archive URI or to the URI given in relative-to.

But... In the `p:unarchive` description I stated that unarchiving a file. `x.xml` from an archive `file:///a/b/c/d.zip` (or with `relative-to` set to this value) results in a base URI of `file:///a/b/c/d.zip/x.xml`.

But I would expect that "Resolving against the archive's name" means the unarchived file's base URI would become `file:///a/b/c/x.xml`?

**Comment by gimsieke** [comment]
> But... In the `p:unarchive` description I stated that unarchiving a file. `x.xml` from an archive `file:///a/b/c/d.zip` (or with `relative-to` set to this value) results in a base URI of `file:///a/b/c/d.zip/x.xml`.

Oh, did you? I think this is not how URI resolution works.

> 
> But I would expect that "Resolving against the archive's name" means the unarchived file's base URI would become `file:///a/b/c/x.xml`?

Yes, more like this.

**Comment by xatapult** [comment]
Yes I did, it's in the current spec. And I did it because it makes sense IMHO. The unarchived file resided *in* the archive, so its base URI should reflect that in some way I think.

Having its base URI say that it was in the directory the archive was in makes no sense to me.

**Comment by xml-project** [comment]
If we say, the relative uri is resolved agains the archives uri followed by a "/", we can satisfy both of you: This is how resolving a URI works (@gimsieke) and it follows the "archives are folders" paradigm (@xatapult)

**Comment by gimsieke** [comment]
The base URI does not necessarily say that the file was in a directory or in an archive. It can mean anything that you make of it, including the future storage location. As a default location for p:store to save the extracted files to, the URI with the archive name in it is absolutely useless while the URI in the directory can be used.

**Comment by xatapult** [comment]
Was that a requirement, using it as a default location for `p:store`? And anyway, who says I always want to store it in the directory the archive is in? 

If you want to use the base URI for that purpose, its actually quite simple: use the `relative-to` option and set this to the directory you want to store the unarchived files to.  

I would prefer to have the default base URI say something about the *provenance* of the document, not about some maybe, maybe not, intended future storage location...
