### ISSUE TITLE
p:xslt and xsl:use-package use

### ISSUE THREAD

**Issue by cmarchand** [xproc/3.0-steps#273]
I do not know if it's an issue, or a question.
When I run saxon on a XSL that uses packages

- with 9.6 I had to list all packages : `-xsl:mainPackage.xsl:package1.xsl:package2.xsl` [Saxon 9.6 commandLine doc](http://www.saxonica.com/documentation9.6/index.html#!using-xsl/commandline)
- with 9.9, this option has been removed, and an internal package resolver is used. But not very well specified. [This part of documentation](http://www.saxonica.com/documentation/index.html#!using-xsl/compiling) is a little more precise, but recommend to use SEF files. And command-line package compilation is not clearly defined...

Do these problems were identified when `p:xslt` has been specified ?

**Comment by gimsieke** [comment]
Because package storage and lookup is implementation-defined as per the XSLT 3.0 spec, it all depends on the XSLT processor and its lookup mechanism. I’m afraid the XProc spec cannot be more specific about it. In the case of Saxon from version 9.8 on, it will boil down to maintaining a configuration file and making it available to Saxon through (XProc-) implementation-defined means. Also if .sef needs to be the format, ad-hoc compilation of XSLT packages from inside an XProc processor might not be supported. 

I’m not sure whether there is anything that we can reasonably specify in this regard.

**Comment by cmarchand** [comment]
Yes, that's the problem.
SEF file or the result of all required packages compiled into one single file. In this case, `p:xslt`specification is enough. But sure, xsl compilation in this case must be out of XProc pipeline.

Thanks for clarifying this, Gerrit.
