### ISSUE TITLE
p:directory-list needs amendment

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#274]
Trying to implement this (again), I found at least two passage, that need some more explanation.

- There is an attribute "uri" in c:file, c:directory and c:other which is not explained anywhere. 

- There is an attribute "content-type**s**" which is not explained. (I think it should be "content-type" anyway).

- Since "@uri" is mandatory, we should adapt "Example 1. Sample Directory List Output for a Single File"

**Comment by gimsieke** [comment]
There was a discussion about `@uri` in #89. 

PR #105 introduced `@uri`, and PR #111 saw it [go away again](https://github.com/xproc/3.0-steps/pull/111/files#diff-fa1e075cbfdf19f98f6e757401454826L90). 

The consensus seemed to have been not to have `@uri` but `@name` and `@xml:base`, but I don’t remember exactly.

In PR #111, I forgot to remove the `@uri` attribute in the RNC schema, I removed it only in the prose. 

Anyway, the other schema changes to `c:directory` et al. (for the file info attributes when `detailed="true"`) that I introduced are now gone since I added them to core30.rnc of the steps repo. 

Once we remember what we agreed upon wrt `@uri` etc., we need to adjust the schema at [3.0-grammar](https://github.com/xproc/3.0-grammar/blob/master/src/main/schema/core30.rnc), at least in order to introduce the file info attributes.

**Comment by xml-project** [comment]
Thanks for the historical reasearch. Not sure what happend with PR #111 . But if I remember right (and thats seems to be confirmed by a short look at the discussion in #89 , we need the uri-attribute because base-uri() does not work the way, we expected it to work.
Anyway: There was no description of the two attributes in PR #105 either.

**Comment by xml-project** [comment]
@gimsieke Yes, you are right. Attribute 'uri' needs just to be removed from the RNC, because we decided that xml:base is the right way to do it.
Apart from that: 'content-types' should be renamed in the RNC and explained in the prose.
Since you are much better in RNC then me: Would you mind to make the changes in RNC and I change the prose?

**Comment by xml-project** [comment]
Changes in RNC are not reflected in the build. Actually, the build was not even updated. Let's see if it is included in the next PR for steps. Otherwise I will ask Norm for help.

**Comment by xml-project** [comment]
Ok, now @gimsieke's changes are reflected in the build.
But I need a short reply from @ndw @gimsieke @xatapult on "content-types". This attribute is optional, but not listed in the detailed list. So I expect it to be present, independed of "detailed".

We need to say, under which circumstances a author can expect the processor to deliver this attribute. Or should we put it in the attributes only available when `detailed=true()`.
