### ISSUE TITLE
Content type of port result on p:text-join

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#319]
With pr #318 the content-types of p:text-join was changed from "text" to "text/plain". I think that was wrong.
There is an attribute "overwrite-content-type" which allows to set the content-type of the result (as long as it is a text content-type). So the correct value for output port "result" IMHO is "text".

**Comment by gimsieke** [comment]
I stumbled over this, too. I thought Norm’s reasoning to use `text/plain` was: By default it needs to be `text/plain` no matter what went into it, since the step cannot make sure that what comes out is still `text/csv` or whatever came in. 

However, `content-types` does not describe the default content type of the result, but all possible content types. And this needs to be `text`. So I agree with you, Achim.

In addition, at one spot in the prose there is `overwrite-content-type`. It needs to be `override-content-type`.

**Comment by xml-project** [comment]
> However, content-types does not describe the default content type of the result, but all possible content types. 

Right:  "XD0042" would be raised for @override-content-type other than "text/plain". This would make this option pretty useless.

**Comment by ndw** [comment]
Sorry. What happened was, I made a pass through where I over-enthusiastically changed the `content-types` of `p:output` from specific media types to shortcuts. I then thought better of that and attempted to undo that mess. In the case of `p:text-join` I was overzealous. It should be "`text`".
