### ISSUE TITLE
Update the text steps

### ISSUE THREAD

**Issue by eriksiegel** [xproc/3.0-steps#38]
The current (201902) version of the text steps is still just a copy/paste kind of thing and needs refactoring/updating. We discussed this in Prague: https://github.com/xproc/Workshop-2019-02/wiki/Meeting-minutes-Tuesday

**Comment by eriksiegel** [comment]
I'm going to break out the text steps into separate files per step, like the standard step library.
The more simple onces (head, tail, join, sort, count) will be moved to the standard steps (we decided this in Prague)

**Comment by eriksiegel** [comment]
We don't need text-insert-at-front/end (as mentioned in Prague) because this can be done with text-join as it is defined now (using the `suffix` and `prefix` option

**Comment by eriksiegel** [comment]
The only text step not in the standard step library, is I think, p:markdown-to-html. @ndw will specify this one.

**Comment by xml-project** [comment]
@eriksiegel You are right we do not need a text-insert at front/end because this can be done with text join. My use case was to insert/use variable- and option values (especially statics) there. This would be easier with an option on the text-join and, as far as I see, it does not come with almost no cost.
So I would argument to have this two optional options.

**Comment by eriksiegel** [comment]
PR in #48
