### ISSUE TITLE
Missing syntax of p:run

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#421]
The syntax (rng) of p:run is commented out.
Maybe you could fix this.

**Comment by gimsieke** [comment]
@ndw I wonder why my [additions to the `p:run` schema](https://github.com/xproc/3.0-grammar/commit/c342840be7044d2c026fb4f2e5c286f9ffa0e3e7) (adding `p:output` primarily) have been reverted in the [next commit](https://github.com/xproc/3.0-grammar/commit/455d72eadf8ff86bed6512b43626bec2bdf9dda5#diff-782a9d1d3da79d74f04eeda2831508f6).

**Comment by gimsieke** [comment]
> 
> 
> @ndw I wonder why my [additions to the `p:run` schema](https://github.com/xproc/3.0-grammar/commit/c342840be7044d2c026fb4f2e5c286f9ffa0e3e7) (adding `p:output` primarily) have been reverted in the [next commit](https://github.com/xproc/3.0-grammar/commit/455d72eadf8ff86bed6512b43626bec2bdf9dda5#diff-782a9d1d3da79d74f04eeda2831508f6).

@ndw This hasn’t been addressed yet. Therefore the [syntax box](https://spec.xproc.org/master/head/run/#d212e0) lacks `p:output`.

**Comment by ndw** [comment]
Right. The problem is that you're approaching the problem from the wrong side. The `p:declare-step` in the `p:run` step will generate the step declaration in the grammar. There's no provision for writing the step declaration in the grammar and referring to it from the step specification. Apologies for the lack of clarity there.

**Comment by ndw** [comment]
Fixed, I believe.
