### ISSUE TITLE
Outdated note in p:directory-list?

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#57]
In [p:directory-list](http://spec.xproc.org/master/head/steps/#c.directory-list) there is a note saying:

> There is no way to specify a list of values using attribute value templates. If the option shortcut syntax is used to provide the include-filter or exclude-filter option, it will consist of a single regular expression. To specify a list of regular expressions, you must use the p:with-option syntax.

Since we now `include-filter` and `exclude-filter` are defined as `xs:string` (whitespace separated lists of regular expressions) I fail to understand what "list" is supposed to mean in this context. Is this box a remnant from the time, we played with `xs:string*`?

**Comment by eriksiegel** [comment]
Ah yes. Data type of both options should be `xs:string*`

**Comment by xml-project** [comment]
@eriksiegel Sure? I thought we opted against it and use a whitespace separated string. (The text says so)

**Comment by gimsieke** [comment]
At least the [change](https://github.com/xproc/3.0-specification/blame/f04a90106807441ddabbf9b6ccfa819905b919bd/steps/src/main/xml/steps/directory-list.xml#L39) where we went from a list of regexes to whitespace-separated regexes is more recent (Jan 29, 2019) than the note that you cited (it’s from Aug 19, 2018).

When looking at the [PR that introduced the change](https://github.com/xproc/3.0-specification/pull/732), I don’t see an approval or a reference to an issue. 

I don’t remember what we decided. The London 2018-06 notes seem to suggest that we went for lists of regexes, and that’s what the Aug 19 notes refers to.

I’m not against space-separated regexes since URIs may not contain whitespace anyway. 

But I’m wondering whether the circumstances that made Norm change this option from “sequence” to “space-separated” also affected other options. The options `include-filter` and `exclude-filter` of `p:load-directory-list` and the attribute `namespace` on `p:import-functions` seem to be affected by the change.

**Comment by xml-project** [comment]
> But I’m wondering whether the circumstances that made Norm change this option from “sequence” to “space-separated” also affected other options. The options include-filter and exclude-filter of p:load-directory-list and the attribute namespace on p:import-functions seem to be affected by the change.

At least `p:unarchived` seems to be affected because there we introduced space separated lists too. May be @ndw can help.

In general I would have a slight tendency for the "list of strings" (xs:string*), but obviously it was decided otherwise.

**Comment by eriksiegel** [comment]
I thought I remembered but now I'm no longer that sure. But: IMHO its a bit silly to go for whitespace separated lists when we have these beautiful language-native sequences of strings as a native datatype...

**Comment by xml-project** [comment]
Related to #58

**Comment by xml-project** [comment]
Fixed with pr #62
