### ISSUE TITLE
Description of p:directory-list needs improvement 

### ISSUE THREAD

**Issue by xml-project** [xproc/3.0-steps#58]
In p:directory-list there is no hint, that the value of option `path` has to be resolved against the relevant baseURI if it is relative. In XProc 1.0 this hint was missing too, but the test in the test suite required this behavior.
I think we should make this explicit.

**Comment by gimsieke** [comment]
Or we can say that `p:urify()` will be applied to `path`. This will allow OS paths for `path`, too (which mainly makes a difference on Windows), but this will also mean that by default it will be resolved against the current working directory if available, rather than against a base URI.

**Comment by xml-project** [comment]
@gimsieke You want a p:urify() inside the step, so the user does not have to call this function themself on the p:with-option? Did I get you right?
Would be fine with me, but to be consistent we should do this everywhere (p:load, p:store etc). And this make the explicit function obsolete, doesn't it?

**Comment by xml-project** [comment]
Second required improvement: The specification says, that an implementation must handle "file:///" but it does not say what happens, if an unsupported scheme is used. I think we need a new error XC... for this case, so it can be caught in a try/catch.

**Comment by gimsieke** [comment]
I withdraw the proposal to magically apply `p:urify()`. One reason is that it is specified as an `xs:anyURI`. The other reason is that, as you said, we’d need to consider applying the same magic to all similar options.

So relative URIs should be resolved to a base URI. But which? The base URI of the document that’s on the DRP or the base URI that is in force in the pipeline document where `p:directory-list` is called (without further `@xml:base` attributes in that pipeline, it would be the pipeline document’s base URI)? Do we have a general principle for this?

An unsupported URI scheme should throw [XD0012](http://spec.xproc.org/master/head/xproc/#err.D0012), I guess. This need not be said explicitly in `p:directory-list` because it is a common error.

**Comment by gimsieke** [comment]
> So relative URIs should be resolved to a base URI. But which? The base URI of the document that’s on the DRP or the base URI that is in force in the pipeline document where `p:directory-list` is called (without further `@xml:base` attributes in that pipeline, it would be the pipeline document’s base URI)? Do we have a general principle for this?

It probably needs to be the pipeline’s base URI because we’d otherwise introduce ultra-subtle dependencies on the DRP document for seemingly innocuous expressions like relative URIs.

**Comment by xml-project** [comment]
I think we should use the same rules we use for p:load/p:store:

> If the href is relative, it is made absolute against the base URI of the element on which it is specified (p:with-option or p:load in the case of a syntactic shortcut value).

I would prefer to have a special error code for "I do not support directory listing of this uri": Think of "http". An XProc processor will typically support this protocoll for p:load. But that does not mean that it also supports the webdav protocol for "http", so can list directories. The same for "ftp": Might be able to resolve a resource (a file), but not be able to list a directory.

This is an instance of the granularity discussion we had some weeks ago. If you can try/catch specific error, the more specific, the better. At least I would strongly argue so.

**Comment by gimsieke** [comment]
I agree. Let’s have a specific dynamic error that says “this URI scheme is not supported for directory listings”
