### ISSUE TITLE
Packaging up a 3.1 release

### ISSUE THREAD

**Issue by ndw** [xproc/3.0-steps#606]
Hi folks,

I think we're closing in on having something we can call 3.1, or at least 3.1 Last Call. I think part of that plan is to publish "official" versions of the additional steps (run, file, os, mail, paged media, text, validation, and (maybe?) Invisible XML).

1. Are we labeling the additional steps 3.0 or 3.1?
2. Are we publishing 8 separate additional specifications, or are we combining them into a single "Optional Steps" document?

What else do we need to do before we call 3.1 "last call"?

**Comment by xml-project** [comment]
> 1.  Are we labeling the additional steps 3.0 or 3.1?

I would prefer to use the same numbering as for the standard step library because it is less confusing and makes communication about implementations easier. 

>    2. Are we publishing 8 separate additional specifications, or are we combining them into a single "Optional Steps" document?

@ndw I guess to have one document improves the publication process, right? If so, I would like to have one document with different sections/chapters, so I can write something like: "My implementation supports all steps of section 4, but none of section 6." 
If not, I would prefer to have different documents. For users this might be more usefull because if something is changed in a document with steps, I do not use, I do not have to care about this.

These are just my 5 cents, but I will agree with whatever you and the others decide. Any thought @gimsieke @xatapult ?

**Comment by gimsieke** [comment]
I don’t have a strong opinion about having a single or multiple optional specs.

**Comment by ndw** [comment]
Okay. I'll take that as a vote for labeling them 3.1 and leaving them separate.
